cloud: ""

services:
  icc:
    name: icc
    deploy: true
    replicaCount: 1
    autoscaling:
      enabled: false
    env:
      # Shared
      DEV_K8S: true

      # Main service
      DEMO_LOGIN: "true"
      DEV: true
      PLT_MAIN_LOGGER_LEVEL: "info"
      VITE_API_BASE_URL: "https://icc.plt"
      VITE_SERVER_URL: "https://icc.plt"
      VITE_DEMO_LOGIN: "DEMO"
      VITE_SUPPORTED_LOGINS: "demo"

      # Metrics
      PLT_METRICS_PROMETHEUS_URL: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"

      # User Manager
      PLT_USER_MANAGER_SUPER_ADMIN_EMAIL: "demo@platformatic.dev"

      # Compliance
      PLT_COMPLIANCE_LOGGER_LEVEL: "info"

      # Control Plane
      PLT_CONTROL_PLANE_LOG_LEVEL: "info"

      # Cron
      PLT_CRON_LOGGER_LEVEL: "info"

      # Trafficante
      PLT_TRAFFICANTE_LOGGER_LEVEL: "info"

      # Scaler
      PLT_SCALER_LOGGER_LEVEL: "info"
      PLT_SCALER_COOLDOWN: 30
      PLT_SCALER_PERIODIC_TRIGGER: 20
      PLT_METRICS_TIME_RANGE: 30

      # Risk service
      PLT_RISK_SERVICE_LOGGER_LEVEL: "info"

      # Risk Cold Storage
      PLT_COLD_STORAGE_LOGGER_LEVEL: "info"
    secrets:
      # Shared
      PLT_ICC_SESSION_SECRET: "session-secret"

      # Main service
      PLT_MAIN_SESSION_SECRET_KEY: "session-test-key"

      # Activities
      PLT_ACTIVITIES_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/activities"

      # User Manager
      PLT_USER_MANAGER_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/user_manager"
      PLT_USER_MANAGER_SESSION_SECRET_KEY: "iNEU1LFsoWlUvWzkKOCwTyTsUQriyg8KmXxpQGxLXxU="

      # Compliance
      PLT_COMPLIANCE_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/compliance"

      # Control Plane
      PLT_CONTROL_PLANE_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/control_plane"
      # Comma separated list of secret keys
      PLT_CONTROL_PLANE_SECRET_KEYS: "test"

      # Cron
      PLT_CRON_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/cron"

      # Trafficante
      PLT_TRAFFICANTE_DATABASE_URL: "postgres://postgres:postgres@dbtrafficante-postgresql.default.svc.cluster.local/trafficante"

      # Scaler
      PLT_SCALER_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/scaler"

      # Risk Cold Storage
      PLT_COLD_STORAGE_DATABASE_URL: postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/cold_storage

  machinist:
    replicaCount: 1
    autoscaling:
      enabled: false
    env:
      PLT_DEV_MODE: true
      PLT_PORT: 3000
      PLT_LOGGER_LEVEL: "debug"
      PLT_K8S_PROVIDER: "k8s"

      PLT_DISABLE_EVENT_EXPORT: true
    secrets: {}
