cloud: ""

services:
  icc:
    name: icc
    deploy: true
    replicaCount: 1
    autoscaling:
      enabled: false
    env:
      # Shared
      DEV_K8S: true
      PLT_ICC_LOGGER_LEVEL: "info"
      PLT_MACHINIST_URL: http://machinist.platformatic.svc.cluster.local:3042
      PLT_EXTERNAL_TRAFFICANTE_URL: http://icc.platformatic.svc.cluster.local:3042/trafficante
      PLT_EXTERNAL_ACTIVITIES_URL: http://icc.platformatic.svc.cluster.local:3042/activities
      PLT_EXTERNAL_COMPLIANCE_URL: http://icc.platformatic.svc.cluster.local:3042/compliance
      PLT_EXTERNAL_CRON_URL: http://icc.platformatic.svc.cluster.local:3042/cron
      PLT_EXTERNAL_USER_MANAGER_URL: http://icc.platformatic.svc.cluster.local:3042/user-manager
      PLT_EXTERNAL_RISK_MANAGER_URL: http://icc.platformatic.svc.cluster.local:3042/risk-manager
      PLT_EXTERNAL_RISK_SERVICE_URL: http://icc.platformatic.svc.cluster.local:3042/risk-service
      PLT_EXTERNAL_METRICS_URL: http://icc.platformatic.svc.cluster.local:3042/metrics
      PLT_EXTERNAL_SCALER_URL: http://icc.platformatic.svc.cluster.local:3042/scaler

      # Main service
      DEMO_LOGIN: "true"
      DEV: true
      VITE_API_BASE_URL: "https://icc.plt"
      VITE_SERVER_URL: "https://icc.plt"
      VITE_DEMO_LOGIN: "DEMO"
      VITE_SUPPORTED_LOGINS: "demo"

      # Metrics
      PLT_METRICS_PROMETHEUS_URL: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"

      # User Manager
      PLT_USER_MANAGER_SUPER_ADMIN_EMAIL: "demo@platformatic.dev"

      # Control Plane
      PLT_CONTROL_PLANE_LOG_LEVEL: "info"

      # Scaler
      PLT_SCALER_COOLDOWN: 30
      PLT_SCALER_PERIODIC_TRIGGER: 20
      PLT_METRICS_TIME_RANGE: 30
    secrets:
      # Shared
      PLT_ICC_SESSION_SECRET: "session-secret"

      # Main service
      PLT_MAIN_SESSION_SECRET_KEY: "session-test-key"

      # Activities
      PLT_ACTIVITIES_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/activities"

      # User Manager
      PLT_USER_MANAGER_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/user_manager"
      PLT_USER_MANAGER_SESSION_SECRET_KEY: "iNEU1LFsoWlUvWzkKOCwTyTsUQriyg8KmXxpQGxLXxU="

      # Compliance
      PLT_COMPLIANCE_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/compliance"

      # Control Plane
      PLT_CONTROL_PLANE_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/control_plane"
      # Comma separated list of secret keys
      PLT_CONTROL_PLANE_SECRET_KEYS: "test"

      # Cron
      PLT_CRON_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/cron"

      # Trafficante
      PLT_TRAFFICANTE_DATABASE_URL: "postgres://postgres:postgres@dbtrafficante-postgresql.default.svc.cluster.local/trafficante"

      # Scaler
      PLT_SCALER_DATABASE_URL: "postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/scaler"

      # Risk Cold Storage
      PLT_COLD_STORAGE_DATABASE_URL: postgres://postgres:postgres@postgresql-dbicc.default.svc.cluster.local/cold_storage

  machinist:
    replicaCount: 1
    autoscaling:
      enabled: false
    env:
      PLT_DEV_MODE: true
      PLT_PORT: 3000
      PLT_LOGGER_LEVEL: "debug"
      PLT_K8S_PROVIDER: "k8s"
      PLT_DISABLE_EVENT_EXPORT: true
    secrets: {}
