cloud: ""

services:
  icc:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    env:
      PLT_MAIN_LOGGER_LEVEL: "warn"
      PLT_COMPLIANCE_LOGGER_LEVEL: "warn"
      PLT_CRON_LOGGER_LEVEL: "warn"
      PLT_CONTROL_PLANE_LOG_LEVEL: "warn"
      PLT_TRAFFICANTE_LOGGER_LEVEL: "warn"
      PLT_SCALER_LOGGER_LEVEL: "warn"
      PLT_RISK_SERVICE_LOGGER_LEVEL: "warn"
      PLT_COLD_STORAGE_LOGGER_LEVEL: "warn"
      PLT_SCALER_COOLDOWN: 300
      PLT_SCALER_PERIODIC_TRIGGER: 60
      PLT_METRICS_TIME_RANGE: 60
    secrets:
      # Shared
      PLT_ICC_SESSION_SECRET: ""
      # Main service
      PLT_GITHUB_OAUTH_CLIENT_ID: ""
      PLT_GITHUB_OAUTH_CLIENT_SECRET: ""
      PLT_GOOGLE_OAUTH_CLIENT_ID: ""
      PLT_GOOGLE_OAUTH_CLIENT_SECRET: ""
      PLT_MAIN_SESSION_SECRET_KEY: ""
      # Activities
      PLT_ACTIVITIES_DATABASE_URL: ""
      # User Manager
      PLT_USER_MANAGER_DATABASE_URL: ""
      PLT_USER_MANAGER_SESSION_SECRET_KEY: ""
      # Compliance
      PLT_COMPLIANCE_DATABASE_URL: ""
      # Control Plane
      PLT_CONTROL_PLANE_DATABASE_URL: ""
      PLT_CONTROL_PLANE_SECRET_KEYS: ""
      # Cron
      PLT_CRON_DATABASE_URL: ""
      # Trafficante
      PLT_TRAFFICANTE_DATABASE_URL: ""
      # Scaler
      PLT_SCALER_DATABASE_URL: ""
      # Risk Cold Storage
      PLT_COLD_STORAGE_DATABASE_URL: ""

  machinist:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    env:
      PLT_LOGGER_LEVEL: "warn"
    secrets: {}
