{{- if .Values.services.icc.deploy }}
---
{{- include "deployment.icc" (list $ .Values.services.icc) }}
{{- end }}
{{- if .Values.services.machinist.deploy }}
---
{{- include "deployment.machinist" (list $ .Values.services.machinist) }}
{{- end }}
