{{- if .Values.icc.deploy }}
---
{{- include "deployment.icc" (list $ .Values.icc) }}
{{- end }}
{{- if .Values.machinist.deploy }}
---
{{- include "deployment.machinist" (list $ .Values.machinist) }}
{{- end }}
