{{- if eq "gcp" .Values.cloud }}
{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.managedCertificates -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ingress.name | default "platformatic" }}
  namespace: {{ .Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" .name) $) | nindent 4 }}
spec:
  domains:
    {{- range .Values.ingress.managedCertificates }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
