{{- if .Values.watt.monitor.enable }}
{{- include "prometheus.podmonitor" (list $ .Values.watt.monitor) }}
{{- end }}

{{- if $.Values.services.icc.monitor.enable -}}
{{- include "prometheus.servicemonitor" (list $ .Values.services.icc) }}
{{- end }}

{{- if $.Values.services.machinist.monitor.enable -}}
{{- include "prometheus.servicemonitor" (list $ .Values.services.machinist) }}
{{- end }}

{{- if and $.Values.services.workflow $.Values.services.workflow.deploy }}
{{- if $.Values.services.workflow.monitor.enable -}}
{{- include "prometheus.servicemonitor" (list $ .Values.services.workflow) }}
{{- end }}
{{- end }}

{{- if and $.Values.services.ebpfSandbox $.Values.services.ebpfSandbox.deploy $.Values.services.ebpfSandbox.monitor }}
{{- if $.Values.services.ebpfSandbox.monitor.enable -}}
{{- include "prometheus.servicemonitor" (list $ .Values.services.ebpfSandbox) }}
{{- end }}
{{- end }}
