{{- if .Values.wattpro.monitor.enable }}
---
{{- include "prometheus.podmonitor" (list $ .Values.wattpro.monitor) }}
{{- end }}

{{- range $service, $val := .Values.services }}
---
{{- if .monitor.enabled -}}
{{- include "prometheus.servicemonitor" (list $ .) }}
{{- end }}
{{- end }}
