{{- range $service, $val := .Values.services }}
{{- if .deploy }}
{{- range $volume, $val := .volumes }}
{{- if eq .existing true}}
  {{ continue }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
  namespace: {{ $.Values.namespace | default "platformatic" }}
spec:
  storageClassName: {{ .storageClass }}
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- with .selectorLabels }}
  selector:
    matchLabels:
      {{- toYaml .| nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
