{{- if .Values.serviceAccount.create -}}
{{- if (.Values.services.machinist.env).PLT_ENABLE_MACHINE_METRICS -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $.Values.namespace | default "platformatic" }}
  name: prometheus-manager
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - prometheusrules
    verbs:
      - get
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-prometheus
  namespace: {{ $.Values.namespace | default "platformatic" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "application.serviceAccountName" . }}
    namespace: {{ $.Values.namespace | default "platformatic" }}
roleRef:
  kind: Role
  name: prometheus-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}