{{/* The docker pull image secret */}}
{{- with .Values.imagePullSecret }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: image-pull-secret
  namespace: {{ include "install.namespace" $ }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" "image-pull-secret") $) | nindent 4 }}
data:
  .dockerconfigjson: {{ include "imagePullSecret.dockerConfig" . | b64enc }}
{{- end }}

{{/* Set ICC generic secrets */}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc
  namespace: {{ include "install.namespace" $ }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
data:
  {{- range $secret, $val := .Values.services.icc.secrets }}
  {{ $secret }}: {{ $val | b64enc }}
  {{- end }}

{{/* Add all enabled ICC login methods */}}

{{- with .Values.services.icc.login_methods.google }}
{{- if .enable }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc-google-oauth
  namespace: {{ include "install.namespace" $ }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" "icc-google-oauth") $) | nindent 4 }}
data:
  client_id: {{ .client_id | b64enc }}
  client_secret: {{ .client_secret | b64enc }}
  valid_emails: {{ .valid_emails | b64enc }}
{{- end }}
{{- end }}

{{- with .Values.services.icc.login_methods.github }}
{{- if .enable }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc-github-oauth
  namespace: {{ include "install.namespace" $ }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" "icc-github-oauth") $) | nindent 4 }}
data:
  client_id: {{ .client_id | b64enc }}
  client_secret: {{ .client_secret | b64enc }}
  valid_emails: {{ .valid_emails | b64enc }}
{{- end }}
{{- end }}

{{/* Setup databases */}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc-databases
  namespace: {{ include "install.namespace" $ }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
data:
  {{- range (include "service.icc.databases" . | trim | split " ") }}
  "{{ . }}": {{ printf "%s/%s" $.Values.services.icc.database_url . | b64enc }}
  {{- end }}

{{/* Setup valkey */}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc-valkey
  namespace: {{ include "install.namespace" $ }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
data:
  apps: {{ $.Values.services.icc.valkey.apps_url | b64enc }}
  icc: {{ $.Values.services.icc.valkey.icc_url | b64enc }}
