{{/* The docker pull image secret */}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.imagePullSecret.name | default "image-pull-secret" }}
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" .name) $) | nindent 4 }}
data:
  .dockerconfigjson: {{ include "imagePullSecret.dockerConfig" . | b64enc }}

{{/* Set the secret keys for user sessions */}}
{{- range $secret, $val := .Values.services.icc.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secret }}
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" $secret) $) | nindent 4 }}
data:
  {{ $secret }}: {{ $val }}
{{- end }}

{{/* Add all enabled ICC login methods */}}

{{- if .Values.services.icc.login_methods.google_oauth.enable }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc_google_oauth
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" .icc_google_oauth) $) | nindent 4 }}
data:
  client_id: .Values.services.icc.login_methods.google_oauth.client_id
  client_secret: .Values.services.icc.login_methods.google_oauth.client_secret
{{- end }}

{{- if .Values.services.icc.login_methods.github_oauth.enable }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc_github_oauth
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" .icc_github_oauth) $) | nindent 4 }}
data:
  client_id: .Values.services.icc.login_methods.github_oauth.client_id
  client_secret: .Values.services.icc.login_methods.github_oauth.client_secret
{{- end }}
