{{/* The docker pull image secret */}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: image-pull-secret
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" "image-pull-secret") $) | nindent 4 }}
data:
  .dockerconfigjson: {{ include "imagePullSecret.dockerConfig" . | b64enc }}

{{/* Set ICC generic secrets */}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
data:
  {{- range $secret, $val := .Values.services.icc.secrets }}
  {{ $secret }}: {{ $val | b64enc }}
  {{- end }}

{{/* Add all enabled ICC login methods */}}

{{- if .Values.services.icc.login_methods.google_oauth.enable }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc-google-oauth
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" "icc-google-oauth") $) | nindent 4 }}
data:
  client_id: {{ .Values.services.icc.login_methods.google_oauth.client_id | b64enc }}
  client_secret: {{ .Values.services.icc.login_methods.google_oauth.client_secret | b64enc }}
{{- end }}

{{- if .Values.services.icc.login_methods.github_oauth.enable }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc-github-oauth
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" "icc-github-oauth") $) | nindent 4 }}
data:
  client_id: {{ .Values.services.icc.login_methods.github_oauth.client_id | b64enc }}
  client_secret: {{ .Values.services.icc.login_methods.github_oauth.client_secret | b64enc }}
{{- end }}

{{/* Setup databases */}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: icc-databases
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
data:
  {{- range (include "service.icc.databases" . | trim | split " ") }}
  "{{ . }}": {{ printf "%s/%s" $.Values.services.icc.database_url . | b64enc }}
  {{- end }}
