---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" $ }}
  namespace: {{ .namespace | default "platformatic" }}
  {{- if eq .Values.cloud "aws"}}
  annotations:
    {{- with .Values.services.icc.elasticacheRoleArn}}
    eks.amazonaws.com/role-arn: {{ . }}
    {{- end}}
  {{- end}}
automountServiceAccountToken: true
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  name: {{ include "application.serviceAccountName" $ }}
spec:
  roleARN: {{ .Values.services.icc.elasticacheRoleArn }}
  serviceAccount: {{ include "application.serviceAccountName" $ }}
  clusterName: "platformatic"
  namespace: {{ .namespace | default "platformatic" }}

{{- range $serviceAccount, $val := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "platformatic" }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .namespace }}
  name: {{ .name }}
rules:
  {{- with .resources.read }}
  - apiGroups:
    {{- range $apiGroup, $val := .apiGroups }}
      - {{ . }}
    {{- end }}
    resources:
    {{- range $kind, $val := .kinds }}
      - {{ . }}
    {{- end }}
    verbs:
      - get
      - list
  {{- end }}
  {{- with .resources.update }}
  - apiGroups:
    {{- range $apiGroup, $val := .apiGroups }}
      - {{ . }}
    {{- end }}
    resources:
    {{- range $kind, $val := .kinds }}
      - {{ . }}
    {{- end }}
    verbs:
      - update
      - patch
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}
  namespace: platformatic
subjects:
  - kind: ServiceAccount
    name: {{ .name }}
    namespace: {{ .namespace | default "platformatic" }}
roleRef:
  kind: Role
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
