# Main service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" $ }}
  namespace: {{ include "install.namespace" $ }}
  {{- if eq .Values.cloud "aws"}}
  annotations:
    {{- with .Values.services.icc.aws}}
    eks.amazonaws.com/role-arn: {{ .role_arn }}
    {{- end}}
  {{- end}}

{{- $accountName := "plt-pod-manager" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $accountName }}
  namespace: {{ include "install.namespace" $ }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $accountName }}
rules:
  - apiGroups:
      - ""
      - apps
      - networking.k8s.io
    resources:
      - pods
      - deployments
      - replicasets
      - replicationcontrollers
      - ingresses
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - ""
      - apps
    resources:
      - deployments
      - replicasets
      - replicationcontrollers
      - pods
    verbs:
      - update
      - patch

{{- $namespaces := include "install.allNamespaces" . | trim | splitList "\n" }}
{{- range $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $accountName }}-{{ . }}
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $accountName }}
    namespace: {{ include "install.namespace" $ }}
roleRef:
  kind: ClusterRole
  name: {{ $accountName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
