---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" $ }}
  namespace: {{ .namespace | default "platformatic" }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- range $serviceAccount, $val := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "platformatic" }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .namespace }}
  name: {{ .name }}
rules:
  {{- with .resources.read }}
  - apiGroups:
    {{- range $apiGroup, $val := .apiGroups }}
      - {{ . }}
    {{- end }}
    resources:
    {{- range $kind, $val := .kinds }}
      - {{ . }}
    {{- end }}
    verbs:
      - get
      - list
  {{- end }}
  {{- with .resources.update }}
  - apiGroups:
    {{- range $apiGroup, $val := .apiGroups }}
      - {{ . }}
    {{- end }}
    resources:
    {{- range $kind, $val := .kinds }}
      - {{ . }}
    {{- end }}
    verbs:
      - update
      - patch
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}
  namespace: platformatic
subjects:
  - kind: ServiceAccount
    name: {{ .name }}
    namespace: {{ .namespace | default "platformatic" }}
roleRef:
  kind: Role
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
