{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: platformatic
  name: pod-manager
rules:
  - apiGroups:
      - ""
      - apps
      - networking.k8s.io
      - autoscaling
      - events.k8s.io
      - batch
    resources:
      - pods
      - deployments
      - replicasets
      - services
      - persistentvolumeclaims
      - ingresses
      - horizontalpodautoscalers
      - events
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
{{- if eq "gcp" .Values.cloud }}
  - apiGroups:
      - networking.gke.io
    resources:
      - managedcertificates
    verbs:
      - get
      - create
      - update
      - patch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-pods
  namespace: platformatic
subjects:
  - kind: ServiceAccount
    name: {{ include "application.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default "platformatic" }}
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-viewer
  namespace: {{ .Values.namespace | default "platformatic" }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-viewer
  namespace: {{ .Values.namespace | default "platformatic" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "application.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default "platformatic" }}
roleRef:
  kind: ClusterRole
  name: node-viewer
  apiGroup: rbac.authorization.k8s.io
{{- end }}
