{{- define "prometheus.servicemonitor" }}
{{- $ := index . 0 }}

{{- with index . 1 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default "platformatic" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- include "application.selectorLabels" (merge (dict "name" .name) $) | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "application.selectorLabels" (merge (dict "name" .name) $) | nindent 6 }}
  endpoints:
    - port: "metrics"
      honorLabels: false
      interval: "15s"
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
          targetLabel: name
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          targetLabel: instance
{{- end }}
{{- end }}
